### ISSUE TITLE
unhandled error in refresh

### ISSUE THREAD

**Issue by insanity54** [zekesonxx/node-yggdrasil#10]
Hi I think there's a problem with the refresh function. it doesn't handle errors.

https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/index.js#L74

```
/home/derp/scripts/mc-screenshot-twitter/node_modules/yggdrasil/lib/index.js:74
      if (data.clientToken !== client) {
              ^

TypeError: Cannot read property 'clientToken' of undefined
    at /home/derp/scripts/mc-screenshot-twitter/node_modules/yggdrasil/lib/index.js:74:15
    at Request._callback (/home/derp/scripts/mc-screenshot-twitter/node_modules/yggdrasil/lib/index.js:30:9)
    at Request.self.callback (/home/derp/scripts/mc-screenshot-twitter/node_modules/yggdrasil/node_modules/request/request.js:121:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/derp/scripts/mc-screenshot-twitter/node_modules/yggdrasil/node_modules/request/request.js:978:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/derp/scripts/mc-screenshot-twitter/node_modules/yggdrasil/node_modules/request/request.js:929:12)
    at emitNone (events.js:72:20)
```

Line 74 of index.js should handle any error received from the callback of r._call. I patched this myself to test, and the error contained string, "Invalid token."

Here's what I think would fix the issue. What do ya'll think?

```
  r.refresh = function (access, client, cb) {
    r._call('refresh', {
      accessToken: access,
      clientToken: client
    }, function (err, data) {
        if (err) cb(err); // <---- added this line
      if (data.clientToken !== client) {
        cb("clientToken assertion failed");
      } else {
        cb(null, data.accessToken, data);
      }
    });
  };
```

**Comment by rom1504** [comment]
Yes that's the right way to do it, do a PR ;)
