### ISSUE TITLE
Better handling of errors

### ISSUE THREAD

**Issue by KaidenP** [zekesonxx/node-yggdrasil#28]
I can't seem to stop this error from ending gracefully, it just crashes node. How can I Handle it?

```
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: Invalid credentials. Invalid username or password.
    at Request._callback (/home/kkprince/WebstormProjects/wrapper-bot/node_modules/yggdrasil/lib/utils.js:23:10)
    at Request.self.callback (/home/kkprince/WebstormProjects/wrapper-bot/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/home/kkprince/WebstormProjects/wrapper-bot/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/home/kkprince/WebstormProjects/wrapper-bot/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

**Comment by KaidenP** [comment]
Well i feel kinda stupid, I found out in nmp I need to handle the error event
